version: '3.8'

services:
  msr-dev-01:
    image: ${CONTAINER_IMAGE}:${CONTAINER_IMAGE_TAG}
    ports:
      - ${HOST_PORT_PREFIX}55:5555
    volumes:
      - ${HOST_MSR_LICENSE_FILE}:/tmp/license.xml
      - ./application.properties:/tmp/application.properties
      # Our Code
      - ../../code/is-packages/WxAssert/:${GUEST_IS_HOME}/packages/WxAssert/
      - ../../code/is-packages/WxAssertTest/:${GUEST_IS_HOME}/packages/WxAssertTest/
      - ../../code/is-packages/WxIsTestTools/:${GUEST_IS_HOME}/packages/WxIsTestTools/
      - ../../code/is-packages/WxIsTestToolsLocalTest/:${GUEST_IS_HOME}/packages/WxIsTestToolsLocalTest/
      - ../../code/is-packages/WxTestDataGen/:${GUEST_IS_HOME}/packages/WxTestDataGen/
      - ../../build/msr/:/mnt/build/
    environment:
      - SAG_IS_LICENSE_FILE=/tmp/license.xml
      - SAG_IS_CONFIG_PROPERTIES=/tmp/application.properties
