<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">nullOrEmpty</value>
  <value name="encodeutf8">true</value>
  <value name="body">U3RyaW5nIG91dGNvbWU9Il9fQUJTRU5UX18iOw0KYm9vbGVhbiBiQ2hhbmdlUGlwZT10cnVlOw0K
DQovLyBwaXBlbGluZQ0KSURhdGFDdXJzb3IgcGlwZWxpbmVDdXJzb3IgPSBwaXBlbGluZS5nZXRD
dXJzb3IoKTsNCglpZihwaXBlbGluZUN1cnNvci5maXJzdCgib2JqVG9Db25zaWRlciIpKSB7DQoJ
CU9iamVjdAlvYmpUb0NvbnNpZGVyID0gcGlwZWxpbmVDdXJzb3IuZ2V0VmFsdWUoKTsNCgkJaWYo
bnVsbCA9PSBvYmpUb0NvbnNpZGVyKQ0KCQkJb3V0Y29tZSA9ICJfX051bGxfXyI7DQoJCWVsc2UN
CgkJCWJDaGFuZ2VQaXBlID0gZmFsc2U7DQoJfQ0KcGlwZWxpbmVDdXJzb3IuZGVzdHJveSgpOw0K
DQppZihiQ2hhbmdlUGlwZSl7DQoJLy8gcGlwZWxpbmUNCglJRGF0YUN1cnNvciBwaXBlbGluZUN1
cnNvcl8xID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7DQoJSURhdGFVdGlsLnB1dCggcGlwZWxpbmVD
dXJzb3JfMSwgIm9ialRvQ29uc2lkZXIiLCBvdXRjb21lICk7DQoJcGlwZWxpbmVDdXJzb3JfMS5k
ZXN0cm95KCk7DQp9</value>
</Values>
